[project]
name = "placement"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lenin1911", email = "leninsamuvel136@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[project.scripts]
placement = "placement:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
